"""
Django settings for tracker_ia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j0e+xt19qmviyt&(xh2q!!ncb95m1xucizh^m%g)0fykjo9+m9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# API Keys
GEMINI_API_KEY = os.getenv("GOOGLE_API_KEY")

# Configuración de Gemini
GEMINI_MODEL = "gemini-2.0-flash-exp"  # Modelo más rápido
GEMINI_MAX_RETRIES = 3
GEMINI_TIMEOUT = 30  # segundos

# Application definition

INSTALLED_APPS = [
  'channels',
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'core',
  'storages',
]

AUTH_USER_MODEL = 'core.Usuario'

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tracker_ia.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'tracker_ia.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
  }
}

# PostgreSQL Configuration Example
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tracker_db',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# CONFIGURACIÓN DE ARCHIVOS (ESTÁTICOS Y MULTIMEDIA)
# ==============================================================================

# 1. Almacenamiento Local (Será el predeterminado para las capturas de YOLO)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
  BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 2. Credenciales de AWS S3 (Para uso específico de las fotos de perfil)
AWS_ACCESS_KEY_ID = "Tu_Clave_de_Acceso_AWS_S3_Aqui"
AWS_SECRET_ACCESS_KEY = "Tu_Clave_Secreta_AWS_S3_Aqui"
AWS_STORAGE_BUCKET_NAME = "tu_bucket_s3_nombre"
AWS_S3_REGION_NAME = "us-east-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False

# NOTA: Las variables DEFAULT_FILE_STORAGE y STORAGES se eliminan
# para que S3 no sea el almacenamiento global por defecto. El almacenamiento
# de S3 se activará únicamente en el modelo `Usuario`.


# Configuración del detector YOLOv8
YOLO_CONFIG = {
  "data_yaml": BASE_DIR / "data" / "data.yaml",
  "weights_dir": BASE_DIR / "core" / "yolo" / "weights",
  "general_model_weights": BASE_DIR / "core" / "yolo" / "weights" / "yolov8m-seg.pt",
  "helmet_model_weights": BASE_DIR / "core" / "yolo" / "weights" / "best.pt",
  "confidence_general": 0.40,
  "confidence_helmet": 0.50,
  "device": "cpu",
  "image_size": 640,
  "helmet_classes": {"driver_with_helmet", "passenger_with_helmet"},
  "no_helmet_classes": {"driver_without_helmet", "passenger_without_helmet"},
  "general_motorcycle_classes": {"motorcycle"},
  "general_person_classes": {"person"},
  "target_fps": 10,
  "min_detection_quality": 0.45,
  "blur_threshold": 100.0,
  "max_processing_fps": 5,
  "require_motorcycle_context": True,
  "motorcycle_proximity_threshold": 1.5,
  "infractor_crop_top_expand": 0.15,
  "infractor_crop_bottom_expand": 0.6,
  "infractor_crop_width_expand": 0.4,
  "save_infractions_dir": BASE_DIR / "media" / "detecciones",
  "draw_boxes": True,
  "box_thickness": 3,
  "box_color_compliant": (0, 255, 0),
  "box_color_infractor": (0, 0, 255),
  "show_labels": True,
  "label_font_scale": 0.6,
  "disable_ultralytics_save": False,
  "save_annotated_video": True,
  "annotated_video_dir": BASE_DIR / "media" / "detecciones_video",
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'panel'
LOGOUT_REDIRECT_URL = 'login'

# Configuración de mensajes de Django
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
  messages.DEBUG: 'debug',
  messages.INFO: 'info',
  messages.SUCCESS: 'success',
  messages.WARNING: 'warning',
  messages.ERROR: 'danger',
}

# Configuración de Channels
ASGI_APPLICATION = 'tracker_ia.asgi.application'
CHANNEL_LAYERS = {
  "default": {
    "BACKEND": "channels.layers.InMemoryChannelLayer"
  }
}
